2017-06-06 15:11:16,201 ERROR: first test message... [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:70]
2017-06-06 15:11:16,899 ERROR: first test message... [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:70]
2017-06-06 15:11:22,592 DEBUG: we are logged out [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:52]
2017-06-06 15:11:22,602 DEBUG: we are in the root [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:15]
2017-06-06 15:11:26,513 DEBUG: we are logged in [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:43]
2017-06-06 15:11:26,525 DEBUG: we are in the root [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:15]
2017-06-06 15:11:32,187 DEBUG: new info added [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:28]
2017-06-06 15:11:32,197 DEBUG: we are in the root [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:15]
2017-06-06 15:12:25,301 ERROR: first test message... [in /Users/Andrey/PycharmProjects/skynet/skynet/views.py:72]
